### ISSUE TITLE
Time Series Results Graphs reversed Accel <==>Displ

### ISSUE THREAD

**Issue by profray** [arkottke/sigmaspectra#3]
Hi Albert,
I think the time series results are reversed, ie accel graph shows displacement and displacement graph shows accel, see the attached screen grab. This is from Version 1.0.0  64-bit windows release. 
![sigmaspectra1 0 0timeseriesscreengrab2017-10-16_17-12-59](https://user-images.githubusercontent.com/26842429/31619953-3a5ebcbe-b296-11e7-8f72-5e0632f447f2.png)

**Comment by arkottke** [comment]
You are totally correct. I changed how I did the plotting in the last
update. I will try to get this fixed this week.

Albert

**Comment by profray** [comment]
I was not concerned about the visuals, but more about the switched series' propagating through the rest of the program/output structure. Nice work BTW

**Comment by arkottke** [comment]
All of the selection is performed on the response spectra so the other
portions of the program should be unaffected. The table of values that
summarize the suite might be switched as well.

Thanks.

On Oct 16, 2017 8:28 AM, "profray" <notifications@github.com> wrote:

I was not concerned about the visuals, but more about the switched series'
propagating through the rest of the program/output structure. Nice work BTW

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/arkottke/sigmaspectra/issues/3#issuecomment-336923375>,
or mute the thread
